### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by thibaudcolas** [mhxion/awesome-discord-communities#106]
I see this project hasn’t been updated in over 2 years – is anyone aware of any alternative curated lists? I’ve found Discord listings hard to navigate as the search isn’t always giving super relevant results for my search terms compared to this list.

**Comment by mhxion** [comment]
Hello.
> this project hasn’t been updated in over 2 years

Slow update is somewhat intentional given that we don't add new communities unless they meet a certain [activity level](https://github.com/mhxion/awesome-discord-communities/blob/main/CONTRIBUTING.md#review-policy), or it'd not be an awesome list ;) Having said that, it is missing a few categories of servers (notably no OpenAI/ChatGPT related server). Though I don't expect many existing servers would be replaced by new, emerging ones. 

But I expect to come back soon. I'm hoping I'll be able to add some of the obvious missing ones.

If you have some immediate suggestions, feel free to [contribute](https://github.com/mhxion/awesome-discord-communities/blob/main/CONTRIBUTING.md) or let me know (:

**Comment by thibaudcolas** [comment]
Thanks @mhxion! I think that answers my question. I guess I would have expected you / other maintainers to close the PRs for communities that don’t meet criteria rather than leave them open? I have a specific community in mind I’d like to add but I’ll check with them first whether that’s ok with them.

**Comment by mhxion** [comment]
> I guess I would have expected you / other maintainers to close the PRs for communities that don’t meet criteria rather than leave them open?

That's on me! I intend to tend to them soon. Every PR with new server submission gets manually reviewed.

> I have a specific community in mind I’d like to add 

Sure : ) 

> but I’ll check with them first whether that’s ok with them.

On that: The way I see it though, as long as a community is public, can be found via Google search, there's nothing wrong with adding it to the list without the owner's/staff's explicit acknowledgement. Awesome lists are essentially site aggregators. We still take the "ask for forgiveness later" approach here though. We let the staff know *after* we've added their community, and ask them to report to us if they wish their community to be removed from the list. And so far no one has : )

**Comment by mhxion** [comment]
`comeback`: #115
