### ISSUE TITLE
Could there be an Open Source section?

### ISSUE THREAD

**Issue by eddiejaoude** [mhxion/awesome-discord-communities#29]
We have a great and inclusive community focusing on Open Source, where would it are listed? More info http://eddiejaoudecommunity.github.io (Discord link at the bottom of the website)

**Comment by mhxion** [comment]
@eddiejaoude I think the name "Open-source" would be too broad and abstract, since it describes almost all of the listed communities. It'd be more consistent if you could target a category name that is more explicit, i.e., looking at your YouTube videos and your Discord channels, the keywords that are most noticeable to me are: Git, GitHub, cloud, JS web frameworks, startups and many more, which fit more into the [Generic category](https://github.com/mhxion/awesome-discord-communities#support-communities), but the [requirements](https://github.com/mhxion/awesome-discord-communities/blob/main/CONTRIBUTING.md#review-policy) to be listed under Generic are much more strict, a server needs to be at least a year old with day-to-day activity on all channels. However, the most common keywords are around [Dev-ops toolchain](https://en.wikipedia.org/wiki/DevOps#Toolchains), and can safely fall into "Dev-ops" category. Let me know what you think, if you have any other category in your mind.

Also those are some really great content on your channel ( :

**Comment by eddiejaoude** [comment]
Thank you @mhxion for the great and positive feedback 🎉 

I am happy with your category suggestion and what you think is best 👍  - let me know what you recommend the next steps are 🤓

**Comment by mhxion** [comment]
@eddiejaoude Thanks for letting me know. I would suggest placing your community under this updated [DevOps category](https://github.com/mhxion/awesome-discord-communities#devops-and-system-administration) (The names are in descending order, so a new community starting with `E` would go after `Data Engineering`). Follow the [PR guide here](https://github.com/mhxion/awesome-discord-communities/blob/main/CONTRIBUTING.md), and for easy conversion of the icon to `webp` you can use [Squoosh](https://squoosh.app/) (with quality 75%). I have yet to automate some of these to ease future contribution, sorry about the extra work.

**Comment by eddiejaoude** [comment]
Thank you for the information 👍 . I have created a PR, hopefully it is ok 🤓 

You could use a GitHub Action to automate various steps, and even to generate the README content from a json file etc
